name: lint

on:
  - push
  - pull_request

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2.3.0
  gomod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go
      - uses: actions/checkout@v2
      - run: make lint-gomod
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: check
